# Generated by Django 3.1.7 on 2022-08-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('nationality', models.CharField(max_length=50)),
                ('height', models.DecimalField(decimal_places=3, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('states', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=200)),
            ],
        ),
    ]
