# Generated by Django 3.1.7 on 2022-09-07 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('match_type', models.CharField(choices=[('MATCH', 'MATCH'), ('TRAINING', 'TRAINING')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Opponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('coach', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('nationality', models.CharField(max_length=50)),
                ('height', models.CharField(default='cm', max_length=30)),
                ('weight', models.CharField(default='kg', max_length=20)),
                ('states', models.CharField(choices=[('Adamawa', 'Adamawa'), ('AkwaIbom', 'AkwaIbom'), ('Abia', 'Abia'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('CrossRiver', 'CrossRiver'), ('Delta', 'Delta'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('Ebonyi', 'Ebonyi'), ('FCT', 'FCT'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kano', 'Kano'), ('Kaduna', 'Kaduna'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], max_length=50)),
                ('bio', models.TextField(max_length=300)),
                ('words', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(choices=[('STRIKER', 'STRIKER'), ('MIDFIELD', 'MIDFIELD'), ('DEFENDER', 'DEFENDER'), ('GOALKEEPER', 'GOALKEEPER')], max_length=10)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('coach', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MatchDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_schedule_type', models.CharField(choices=[('MATCH', 'MATCH'), ('TRAINING', 'TRAINING')], max_length=50)),
                ('result', models.CharField(blank=True, max_length=20)),
                ('player_of_the_match', models.CharField(blank=True, max_length=200)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.match')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.opponent')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.opponent'),
        ),
        migrations.AddField(
            model_name='match',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.team'),
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.IntegerField()),
                ('goal_type', models.CharField(choices=[('OWN GOAL', 'OWN GOAL'), ('NORMAL GOAL', 'NORMAL GOAL')], max_length=20)),
                ('time', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.playerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('RED', 'RED'), ('YELLOW', 'YELLOW')], max_length=20)),
                ('booked_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.playerinfo')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.match')),
            ],
        ),
    ]
