# Generated by Django 3.1.7 on 2022-08-27 18:51

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_playerinfo_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinfo',
            name='image',
            field=models.ImageField(default=builtins.dir, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
